baseURL = "https://radu.ga/"
languageCode = "en-us"
title = "RADUGA"
theme = "smol"

[params]
    subtitle = "small cloud for friends (alpha)"
    dateFmt = "02.01.2006 15:04"

[[menu.main]]
    identifier = "tos"
    name = "tos"
    url = "/tos"
    weight = 1 

[[menu.main]]
    identifier = "privacy"
    name = "privacy"
    url = "/privacy"
    weight = 2

[[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/post"
    weight = 3 

[[menu.main]]
    identifier = "pve"
    name = "pve"
    url = "//pve.radu.ga"
    weight = 4

[[menu.main]]
    identifier = "ocis"
    name = "ocis"
    url = "//ocis.radu.ga"
    weight = 5

[[menu.main]]
    identifier = "share"
    name = "share"
    url = "//s.radu.ga"
    weight = 6

[[menu.main]]
    identifier = "whois"
    name = "whois"
    url = "//ip.radu.ga"
    weight = 7

[[menu.footer]]
    name = "mail"
    url = "mailto:raduga@radu.ga"
    weight = 1 

[[menu.footer]]
    name = "github"
    url = "//github.com/radudotga"
    weight = 2 

[[menu.footer]]
    name = "x"
    url = "//x.com/radudotga"
    weight = 3 

[[menu.footer]]
    name = "telegram"
    url = "//t.me/radudotga"
    weight = 4

[[menu.footer]]
    name = "status"
    url = "//my.okerr.com/status/n7x8eheuw2/raduga"
    weight = 5
